# multi-gpu
env = AQ_DRM_DEVICES,/dev/dri/nvidia-egpu:/dev/dri/amd-igpu

# Multi-GPU (or hybrid graphics) not working for monitors attached to Nvidia GPU 
env = AQ_FORCE_LINEAR_BLIT=0

# Nvidia GPU Environment variables
#env = LIBVA_DRIVER_NAME,nvidia
#env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# VA-API hardware video acceleration
env = NVD_BACKEND,direct

# Flickering in Electron / CEF apps
env = ELECTRON_OZONE_PLATFORM_HINT,auto

cursor {
  no_hardware_cursors = true
}
opengl {
  nvidia_anti_flicker = false
}
